add confirmation modal and cancel button
Alina-Rosenbusch/Capstone-Arena-App pull request #12
Opened 2023-07-28 13:51 UTC by Alina-Rosenbusch

Hey, I implemented a new function into my app, which is pre step for a delete function. Please have a look at this step 😁.

2023-07-28 15:22 UTC, Roland-Hufnagel requested changes
Hi Alina, I was really wondering about the DB-Connection in your code. Then I saw that you did US6 before. Okay. 
I did not find a vercel deployment. Haven't you deployed it yet?
Nevertheless I left some comments for you. Please try to adapt your code.

2023-07-28 15:22 UTC, Roland-Hufnagel commented on components/HomeArenaList/index.js
> +  //Delete confirmation
please remove unnecessary comments

2023-07-28 15:22 UTC, Roland-Hufnagel commented on components/HomeArenaList/index.js
>              <p className="entry_date">{formatDate(entry.date)}</p>
Ahh! Here you use classnames. We don't want to use Classnames since we are working with styled-components.

2023-07-31 09:44 UTC, Roland-Hufnagel requested changes
Hi Alina, you did a good refactoring but there is still a bug with your lists. Please fix this and then you got it 👍

2023-07-31 09:44 UTC, Roland-Hufnagel commented on components/ArenaList/index.js
> +          <StyledArenaListWrapper key={arena._id}>
While mapping now you create a lot of ``<ul>``s. That is not what you want. You want one ``<ul>``as a wrapper around and then with the map-function create the ``<li>``s. (you can check it in the dev-tools)

2023-07-31 09:44 UTC, Roland-Hufnagel commented on components/HomeArenaList/index.js
> +          <StyledHomeArenaWrapper key={entry._id}>
Here is the same point as above. You create a lot of ``<ul>``s instead of ``<li>``s.

2023-07-31 10:20 UTC, Kheirah approved these changes
Looking good!

2023-07-31 10:39 UTC, merged